[package]
name = "boxes-mask"
version = "0.2.1"
edition = "2021"

[lib]
name = "boxes_mask"
crate-type = ["cdylib"]

[dependencies]
ffrwd-node = { git = "https://github.com/imbcmdth/ffrwd-node", tag = "v0.2.0" }
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.151"
