[package]
name = "rfdetr-common"
version = "0.2.0"
edition = "2021"

[lib]
name = "rfdetr_common"

[dependencies]
ffrwd-node = { git = "https://github.com/imbcmdth/ffrwd-node", tag = "v0.2.0" }
ffrwd-frame = { git = "https://github.com/imbcmdth/ffrwd-frame", tag = "v0.1.1" }
serde = { version = "1.0.229", features = ["derive"] }
wit-bindgen = "0.57.1"

[dev-dependencies]
serde_json = "1.0.151"
