[package]
name = "detect-plates"
version = "0.2.0"
edition = "2021"

[lib]
name = "detect_plates"
crate-type = ["cdylib"]

[dependencies]
ffrwd-node = { git = "https://github.com/imbcmdth/ffrwd-node", tag = "v0.2.0" }
rfdetr-common = { path = "../common" }

[dev-dependencies]
serde_json = "1.0.151"
